# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExecutorsUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExecutorWindow(object):
    def setupUi(self, ExecutorWindow):
        ExecutorWindow.setObjectName("ExecutorWindow")
        ExecutorWindow.resize(470, 370)
        ExecutorWindow.setMinimumSize(QtCore.QSize(470, 370))
        ExecutorWindow.setMaximumSize(QtCore.QSize(1410, 370))
        self.centralwidget = QtWidgets.QWidget(ExecutorWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(470, 350))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_quest = QtWidgets.QFrame(self.centralwidget)
        self.frame_quest.setMinimumSize(QtCore.QSize(470, 350))
        self.frame_quest.setMaximumSize(QtCore.QSize(470, 350))
        self.frame_quest.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.frame_quest.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_quest.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_quest.setLineWidth(2)
        self.frame_quest.setObjectName("frame_quest")
        self.txt_quest = QtWidgets.QTextEdit(self.frame_quest)
        self.txt_quest.setGeometry(QtCore.QRect(10, 10, 450, 240))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.txt_quest.setFont(font)
        self.txt_quest.setStyleSheet("")
        self.txt_quest.setFrameShape(QtWidgets.QFrame.Box)
        self.txt_quest.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txt_quest.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_quest.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_quest.setReadOnly(True)
        self.txt_quest.setObjectName("txt_quest")
        self.btn_ok_quest = QtWidgets.QPushButton(self.frame_quest)
        self.btn_ok_quest.setGeometry(QtCore.QRect(60, 270, 70, 60))
        self.btn_ok_quest.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_ok_quest.setMaximumSize(QtCore.QSize(70, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ok_quest.setFont(font)
        self.btn_ok_quest.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 255);\n"
"    \n"
"}\n"
"\n"
"QPushButton:enabled\n"
"{    \n"
"    color: rgb(0,0, 0);\n"
"}\n"
"QPushButton:disabled\n"
"{    \n"
"    color: rgb(175, 175, 175);\n"
"}")
        self.btn_ok_quest.setObjectName("btn_ok_quest")
        self.btn_cancel_quest = QtWidgets.QPushButton(self.frame_quest)
        self.btn_cancel_quest.setGeometry(QtCore.QRect(270, 270, 150, 60))
        self.btn_cancel_quest.setMinimumSize(QtCore.QSize(150, 60))
        self.btn_cancel_quest.setMaximumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel_quest.setFont(font)
        self.btn_cancel_quest.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 255);\n"
"    \n"
"}\n"
"\n"
"QPushButton:enabled\n"
"{    \n"
"    color: rgb(0,0, 0);\n"
"}\n"
"QPushButton:disabled\n"
"{    \n"
"    color: rgb(175, 175, 175);\n"
"}")
        self.btn_cancel_quest.setObjectName("btn_cancel_quest")
        self.horizontalLayout.addWidget(self.frame_quest)
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setMinimumSize(QtCore.QSize(470, 350))
        self.frame_main.setMaximumSize(QtCore.QSize(470, 350))
        self.frame_main.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.frame_main.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setLineWidth(2)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.frame_main)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.combo_Names = QtWidgets.QComboBox(self.frame)
        self.combo_Names.setGeometry(QtCore.QRect(10, 10, 450, 60))
        self.combo_Names.setMinimumSize(QtCore.QSize(0, 60))
        self.combo_Names.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.combo_Names.setFont(font)
        self.combo_Names.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.combo_Names.setEditable(False)
        self.combo_Names.setObjectName("combo_Names")
        self.lbl_name = QtWidgets.QLabel(self.frame)
        self.lbl_name.setGeometry(QtCore.QRect(120, 90, 330, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_name.setFont(font)
        self.lbl_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_name.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_name.setObjectName("lbl_name")
        self.lbl_rank = QtWidgets.QLabel(self.frame)
        self.lbl_rank.setGeometry(QtCore.QRect(170, 140, 245, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_rank.setFont(font)
        self.lbl_rank.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_rank.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_rank.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_rank.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_rank.setObjectName("lbl_rank")
        self.lbl_txt1 = QtWidgets.QLabel(self.frame)
        self.lbl_txt1.setGeometry(QtCore.QRect(0, 90, 100, 37))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_txt1.setFont(font)
        self.lbl_txt1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_txt1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_txt1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_txt1.setObjectName("lbl_txt1")
        self.lbl_txt2 = QtWidgets.QLabel(self.frame)
        self.lbl_txt2.setGeometry(QtCore.QRect(20, 140, 125, 37))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_txt2.setFont(font)
        self.lbl_txt2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_txt2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_txt2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_txt2.setObjectName("lbl_txt2")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_main)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_add = QtWidgets.QPushButton(self.frame_2)
        self.btn_add.setGeometry(QtCore.QRect(10, 10, 160, 60))
        self.btn_add.setMinimumSize(QtCore.QSize(160, 60))
        self.btn_add.setMaximumSize(QtCore.QSize(160, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add.setFont(font)
        self.btn_add.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 255);\n"
"    \n"
"}\n"
"\n"
"QPushButton:enabled\n"
"{    \n"
"    color: rgb(0,0, 0);\n"
"}\n"
"QPushButton:disabled\n"
"{    \n"
"    color: rgb(175, 175, 175);\n"
"}")
        self.btn_add.setObjectName("btn_add")
        self.btn_ok_select = QtWidgets.QPushButton(self.frame_2)
        self.btn_ok_select.setGeometry(QtCore.QRect(380, 10, 70, 60))
        self.btn_ok_select.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_ok_select.setMaximumSize(QtCore.QSize(70, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ok_select.setFont(font)
        self.btn_ok_select.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 255);\n"
"    \n"
"}\n"
"\n"
"QPushButton:enabled\n"
"{    \n"
"    color: rgb(0,0, 0);\n"
"}\n"
"QPushButton:disabled\n"
"{    \n"
"    color: rgb(175, 175, 175);\n"
"}")
        self.btn_ok_select.setObjectName("btn_ok_select")
        self.btn_del = QtWidgets.QPushButton(self.frame_2)
        self.btn_del.setGeometry(QtCore.QRect(190, 10, 160, 60))
        self.btn_del.setMinimumSize(QtCore.QSize(160, 60))
        self.btn_del.setMaximumSize(QtCore.QSize(160, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_del.setFont(font)
        self.btn_del.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 255);\n"
"    \n"
"}\n"
"\n"
"QPushButton:enabled\n"
"{    \n"
"    color: rgb(0,0, 0);\n"
"}\n"
"QPushButton:disabled\n"
"{    \n"
"    color: rgb(175, 175, 175);\n"
"}")
        self.btn_del.setObjectName("btn_del")
        self.btn_cancel_select = QtWidgets.QPushButton(self.frame_2)
        self.btn_cancel_select.setGeometry(QtCore.QRect(60, 80, 160, 60))
        self.btn_cancel_select.setMinimumSize(QtCore.QSize(160, 60))
        self.btn_cancel_select.setMaximumSize(QtCore.QSize(160, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel_select.setFont(font)
        self.btn_cancel_select.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 255);\n"
"    \n"
"}\n"
"\n"
"QPushButton:enabled\n"
"{    \n"
"    color: rgb(0,0, 0);\n"
"}\n"
"QPushButton:disabled\n"
"{    \n"
"    color: rgb(175, 175, 175);\n"
"}")
        self.btn_cancel_select.setObjectName("btn_cancel_select")
        self.btn_exit = QtWidgets.QPushButton(self.frame_2)
        self.btn_exit.setGeometry(QtCore.QRect(280, 80, 160, 60))
        self.btn_exit.setMinimumSize(QtCore.QSize(160, 60))
        self.btn_exit.setMaximumSize(QtCore.QSize(160, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 255);\n"
"    \n"
"}\n"
"\n"
"QPushButton:enabled\n"
"{    \n"
"    color: rgb(0,0, 0);\n"
"}\n"
"QPushButton:disabled\n"
"{    \n"
"    color: rgb(175, 175, 175);\n"
"}")
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame_main)
        self.frame_warning = QtWidgets.QFrame(self.centralwidget)
        self.frame_warning.setMinimumSize(QtCore.QSize(470, 350))
        self.frame_warning.setMaximumSize(QtCore.QSize(470, 350))
        self.frame_warning.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.frame_warning.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_warning.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_warning.setLineWidth(2)
        self.frame_warning.setObjectName("frame_warning")
        self.txt_warning = QtWidgets.QTextEdit(self.frame_warning)
        self.txt_warning.setGeometry(QtCore.QRect(10, 10, 450, 240))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.txt_warning.setFont(font)
        self.txt_warning.setStyleSheet("")
        self.txt_warning.setFrameShape(QtWidgets.QFrame.Box)
        self.txt_warning.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txt_warning.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_warning.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_warning.setReadOnly(True)
        self.txt_warning.setObjectName("txt_warning")
        self.btn_ok_warning = QtWidgets.QPushButton(self.frame_warning)
        self.btn_ok_warning.setGeometry(QtCore.QRect(200, 270, 70, 60))
        self.btn_ok_warning.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_ok_warning.setMaximumSize(QtCore.QSize(70, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ok_warning.setFont(font)
        self.btn_ok_warning.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 255);\n"
"    \n"
"}\n"
"\n"
"QPushButton:enabled\n"
"{    \n"
"    color: rgb(0,0, 0);\n"
"}\n"
"QPushButton:disabled\n"
"{    \n"
"    color: rgb(175, 175, 175);\n"
"}")
        self.btn_ok_warning.setObjectName("btn_ok_warning")
        self.horizontalLayout.addWidget(self.frame_warning)
        self.frame_main.raise_()
        self.frame_warning.raise_()
        self.frame_quest.raise_()
        ExecutorWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ExecutorWindow)
        self.statusbar.setObjectName("statusbar")
        ExecutorWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ExecutorWindow)
        QtCore.QMetaObject.connectSlotsByName(ExecutorWindow)

    def retranslateUi(self, ExecutorWindow):
        _translate = QtCore.QCoreApplication.translate
        ExecutorWindow.setWindowTitle(_translate("ExecutorWindow", "SPG-023MK"))
        self.txt_quest.setMarkdown(_translate("ExecutorWindow", "**ИНФОРМАЦИЯ**\n"
"\n"
""))
        self.txt_quest.setHtml(_translate("ExecutorWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:20pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:13px; margin-bottom:13px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ИНФОРМАЦИЯ</p></body></html>"))
        self.btn_ok_quest.setText(_translate("ExecutorWindow", "Ok"))
        self.btn_cancel_quest.setText(_translate("ExecutorWindow", "Отмена"))
        self.lbl_name.setText(_translate("ExecutorWindow", "Пупкин П. П. "))
        self.lbl_rank.setText(_translate("ExecutorWindow", "слесарь"))
        self.lbl_txt1.setText(_translate("ExecutorWindow", "Ф. И. О."))
        self.lbl_txt2.setText(_translate("ExecutorWindow", "Должность"))
        self.btn_add.setText(_translate("ExecutorWindow", "Добавить"))
        self.btn_ok_select.setText(_translate("ExecutorWindow", "Ok"))
        self.btn_del.setText(_translate("ExecutorWindow", "Удалить"))
        self.btn_cancel_select.setText(_translate("ExecutorWindow", "Отмена"))
        self.btn_exit.setText(_translate("ExecutorWindow", "Выход"))
        self.txt_warning.setMarkdown(_translate("ExecutorWindow", "**ПРЕДУПРЕЖДЕНИЕ**\n"
"\n"
""))
        self.txt_warning.setHtml(_translate("ExecutorWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:20pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:13px; margin-bottom:13px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ПРЕДУПРЕЖДЕНИЕ</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:13px; margin-bottom:13px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_ok_warning.setText(_translate("ExecutorWindow", "Ok"))
