# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'amorts_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AmortsWindow(object):
    def setupUi(self, AmortsWindow):
        AmortsWindow.setObjectName("AmortsWindow")
        AmortsWindow.resize(645, 665)
        AmortsWindow.setMinimumSize(QtCore.QSize(645, 665))
        AmortsWindow.setMaximumSize(QtCore.QSize(645, 665))
        self.centralwidget = QtWidgets.QWidget(AmortsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_parameters = QtWidgets.QFrame(self.centralwidget)
        self.frame_parameters.setGeometry(QtCore.QRect(15, 10, 615, 560))
        self.frame_parameters.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_parameters.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_parameters.setLineWidth(2)
        self.frame_parameters.setObjectName("frame_parameters")
        self.lbl_comp_max = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_comp_max.setGeometry(QtCore.QRect(370, 465, 110, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_comp_max.setFont(font)
        self.lbl_comp_max.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_comp_max.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_comp_max.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_comp_max.setObjectName("lbl_comp_max")
        self.lbl_txt9 = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_txt9.setGeometry(QtCore.QRect(20, 510, 340, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_txt9.setFont(font)
        self.lbl_txt9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_txt9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_txt9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_txt9.setObjectName("lbl_txt9")
        self.lbl_txt5 = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_txt5.setGeometry(QtCore.QRect(20, 420, 340, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_txt5.setFont(font)
        self.lbl_txt5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_txt5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_txt5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_txt5.setObjectName("lbl_txt5")
        self.lbl_recoil_min = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_recoil_min.setGeometry(QtCore.QRect(370, 330, 110, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_recoil_min.setFont(font)
        self.lbl_recoil_min.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_recoil_min.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_recoil_min.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_recoil_min.setObjectName("lbl_recoil_min")
        self.lbl_txt3 = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_txt3.setGeometry(QtCore.QRect(20, 65, 575, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_txt3.setFont(font)
        self.lbl_txt3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_txt3.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_txt3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_txt3.setObjectName("lbl_txt3")
        self.lbl_length_min = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_length_min.setGeometry(QtCore.QRect(430, 105, 110, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_length_min.setFont(font)
        self.lbl_length_min.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_length_min.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_length_min.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_length_min.setObjectName("lbl_length_min")
        self.lbl_temper = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_temper.setGeometry(QtCore.QRect(430, 510, 110, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_temper.setFont(font)
        self.lbl_temper.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_temper.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_temper.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_temper.setObjectName("lbl_temper")
        self.lbl_length_max = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_length_max.setGeometry(QtCore.QRect(430, 150, 110, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_length_max.setFont(font)
        self.lbl_length_max.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_length_max.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_length_max.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_length_max.setObjectName("lbl_length_max")
        self.lbl_txt4 = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_txt4.setGeometry(QtCore.QRect(20, 105, 340, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_txt4.setFont(font)
        self.lbl_txt4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_txt4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_txt4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_txt4.setObjectName("lbl_txt4")
        self.lbl_txt6 = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_txt6.setGeometry(QtCore.QRect(20, 330, 340, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_txt6.setFont(font)
        self.lbl_txt6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_txt6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_txt6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_txt6.setObjectName("lbl_txt6")
        self.lbl_comp_min = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_comp_min.setGeometry(QtCore.QRect(370, 420, 110, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_comp_min.setFont(font)
        self.lbl_comp_min.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_comp_min.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_comp_min.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_comp_min.setObjectName("lbl_comp_min")
        self.lbl_recoil_max = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_recoil_max.setGeometry(QtCore.QRect(370, 375, 110, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_recoil_max.setFont(font)
        self.lbl_recoil_max.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_recoil_max.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_recoil_max.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_recoil_max.setObjectName("lbl_recoil_max")
        self.combo_Names = QtWidgets.QComboBox(self.frame_parameters)
        self.combo_Names.setGeometry(QtCore.QRect(20, 14, 575, 40))
        self.combo_Names.setMinimumSize(QtCore.QSize(0, 40))
        self.combo_Names.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.combo_Names.setFont(font)
        self.combo_Names.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.combo_Names.setEditable(False)
        self.combo_Names.setObjectName("combo_Names")
        self.lbl_txt4_2 = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_txt4_2.setGeometry(QtCore.QRect(20, 150, 340, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_txt4_2.setFont(font)
        self.lbl_txt4_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_txt4_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_txt4_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_txt4_2.setObjectName("lbl_txt4_2")
        self.lbl_txt5_2 = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_txt5_2.setGeometry(QtCore.QRect(20, 465, 340, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_txt5_2.setFont(font)
        self.lbl_txt5_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_txt5_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_txt5_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_txt5_2.setObjectName("lbl_txt5_2")
        self.lbl_txt6_2 = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_txt6_2.setGeometry(QtCore.QRect(20, 375, 340, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_txt6_2.setFont(font)
        self.lbl_txt6_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_txt6_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_txt6_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_txt6_2.setObjectName("lbl_txt6_2")
        self.lbl_txt4_3 = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_txt4_3.setGeometry(QtCore.QRect(20, 195, 340, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_txt4_3.setFont(font)
        self.lbl_txt4_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_txt4_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_txt4_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_txt4_3.setObjectName("lbl_txt4_3")
        self.lbl_hod = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_hod.setGeometry(QtCore.QRect(430, 195, 110, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_hod.setFont(font)
        self.lbl_hod.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_hod.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_hod.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_hod.setObjectName("lbl_hod")
        self.lbl_txt4_4 = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_txt4_4.setGeometry(QtCore.QRect(20, 285, 340, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_txt4_4.setFont(font)
        self.lbl_txt4_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_txt4_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_txt4_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_txt4_4.setObjectName("lbl_txt4_4")
        self.lbl_speed_1 = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_speed_1.setGeometry(QtCore.QRect(370, 285, 110, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_speed_1.setFont(font)
        self.lbl_speed_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_speed_1.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_speed_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_speed_1.setObjectName("lbl_speed_1")
        self.lbl_txt4_6 = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_txt4_6.setGeometry(QtCore.QRect(20, 240, 340, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_txt4_6.setFont(font)
        self.lbl_txt4_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_txt4_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_txt4_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_txt4_6.setObjectName("lbl_txt4_6")
        self.lbl_adapter = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_adapter.setGeometry(QtCore.QRect(430, 240, 110, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_adapter.setFont(font)
        self.lbl_adapter.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_adapter.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_adapter.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_adapter.setObjectName("lbl_adapter")
        self.lbl_speed_2 = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_speed_2.setGeometry(QtCore.QRect(490, 285, 110, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_speed_2.setFont(font)
        self.lbl_speed_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_speed_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_speed_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_speed_2.setObjectName("lbl_speed_2")
        self.lbl_comp_min_2 = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_comp_min_2.setGeometry(QtCore.QRect(490, 420, 110, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_comp_min_2.setFont(font)
        self.lbl_comp_min_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_comp_min_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_comp_min_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_comp_min_2.setObjectName("lbl_comp_min_2")
        self.lbl_comp_max_2 = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_comp_max_2.setGeometry(QtCore.QRect(490, 465, 110, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_comp_max_2.setFont(font)
        self.lbl_comp_max_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_comp_max_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_comp_max_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_comp_max_2.setObjectName("lbl_comp_max_2")
        self.lbl_recoil_min_2 = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_recoil_min_2.setGeometry(QtCore.QRect(490, 330, 110, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_recoil_min_2.setFont(font)
        self.lbl_recoil_min_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_recoil_min_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_recoil_min_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_recoil_min_2.setObjectName("lbl_recoil_min_2")
        self.lbl_recoil_max_2 = QtWidgets.QLabel(self.frame_parameters)
        self.lbl_recoil_max_2.setGeometry(QtCore.QRect(490, 375, 110, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_recoil_max_2.setFont(font)
        self.lbl_recoil_max_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_recoil_max_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_recoil_max_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_recoil_max_2.setObjectName("lbl_recoil_max_2")
        self.frame_btn = QtWidgets.QFrame(self.centralwidget)
        self.frame_btn.setGeometry(QtCore.QRect(15, 567, 615, 80))
        self.frame_btn.setMinimumSize(QtCore.QSize(615, 80))
        self.frame_btn.setMaximumSize(QtCore.QSize(615, 80))
        self.frame_btn.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btn.setLineWidth(2)
        self.frame_btn.setObjectName("frame_btn")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_btn)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add = QtWidgets.QPushButton(self.frame_btn)
        self.btn_add.setMinimumSize(QtCore.QSize(140, 40))
        self.btn_add.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btn_add.setFont(font)
        self.btn_add.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 255);\n"
"    \n"
"}")
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        self.btn_change = QtWidgets.QPushButton(self.frame_btn)
        self.btn_change.setMinimumSize(QtCore.QSize(140, 40))
        self.btn_change.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btn_change.setFont(font)
        self.btn_change.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 255);\n"
"    \n"
"}")
        self.btn_change.setObjectName("btn_change")
        self.horizontalLayout.addWidget(self.btn_change)
        self.btn_del = QtWidgets.QPushButton(self.frame_btn)
        self.btn_del.setMinimumSize(QtCore.QSize(140, 40))
        self.btn_del.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btn_del.setFont(font)
        self.btn_del.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 255);\n"
"    \n"
"}")
        self.btn_del.setObjectName("btn_del")
        self.horizontalLayout.addWidget(self.btn_del)
        self.btn_exit = QtWidgets.QPushButton(self.frame_btn)
        self.btn_exit.setMinimumSize(QtCore.QSize(140, 40))
        self.btn_exit.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 255);\n"
"    \n"
"}")
        self.btn_exit.setObjectName("btn_exit")
        self.horizontalLayout.addWidget(self.btn_exit)
        self.frame_quest = QtWidgets.QFrame(self.centralwidget)
        self.frame_quest.setGeometry(QtCore.QRect(610, -160, 555, 251))
        self.frame_quest.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.frame_quest.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_quest.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_quest.setLineWidth(2)
        self.frame_quest.setObjectName("frame_quest")
        self.txt_quest = QtWidgets.QTextEdit(self.frame_quest)
        self.txt_quest.setGeometry(QtCore.QRect(8, 14, 539, 155))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.txt_quest.setFont(font)
        self.txt_quest.setStyleSheet("")
        self.txt_quest.setFrameShape(QtWidgets.QFrame.Box)
        self.txt_quest.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txt_quest.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_quest.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_quest.setReadOnly(True)
        self.txt_quest.setObjectName("txt_quest")
        self.btn_ok_quest = QtWidgets.QPushButton(self.frame_quest)
        self.btn_ok_quest.setGeometry(QtCore.QRect(150, 178, 73, 61))
        self.btn_ok_quest.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_ok_quest.setMaximumSize(QtCore.QSize(400, 120))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ok_quest.setFont(font)
        self.btn_ok_quest.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 255);\n"
"    \n"
"}")
        self.btn_ok_quest.setObjectName("btn_ok_quest")
        self.btn_cancel_quest = QtWidgets.QPushButton(self.frame_quest)
        self.btn_cancel_quest.setGeometry(QtCore.QRect(312, 178, 141, 57))
        self.btn_cancel_quest.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_cancel_quest.setMaximumSize(QtCore.QSize(400, 120))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel_quest.setFont(font)
        self.btn_cancel_quest.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 255);\n"
"    \n"
"}")
        self.btn_cancel_quest.setObjectName("btn_cancel_quest")
        self.frame_warning = QtWidgets.QFrame(self.centralwidget)
        self.frame_warning.setGeometry(QtCore.QRect(-530, -150, 555, 251))
        self.frame_warning.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.frame_warning.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_warning.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_warning.setLineWidth(2)
        self.frame_warning.setObjectName("frame_warning")
        self.txt_warning = QtWidgets.QTextEdit(self.frame_warning)
        self.txt_warning.setGeometry(QtCore.QRect(8, 14, 539, 155))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.txt_warning.setFont(font)
        self.txt_warning.setStyleSheet("")
        self.txt_warning.setFrameShape(QtWidgets.QFrame.Box)
        self.txt_warning.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txt_warning.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_warning.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_warning.setReadOnly(True)
        self.txt_warning.setObjectName("txt_warning")
        self.btn_ok_warning = QtWidgets.QPushButton(self.frame_warning)
        self.btn_ok_warning.setGeometry(QtCore.QRect(240, 178, 73, 61))
        self.btn_ok_warning.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_ok_warning.setMaximumSize(QtCore.QSize(400, 120))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ok_warning.setFont(font)
        self.btn_ok_warning.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 255);\n"
"    \n"
"}")
        self.btn_ok_warning.setObjectName("btn_ok_warning")
        AmortsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AmortsWindow)
        QtCore.QMetaObject.connectSlotsByName(AmortsWindow)

    def retranslateUi(self, AmortsWindow):
        _translate = QtCore.QCoreApplication.translate
        AmortsWindow.setWindowTitle(_translate("AmortsWindow", "Амортизаторы"))
        self.lbl_comp_max.setText(_translate("AmortsWindow", "0"))
        self.lbl_txt9.setText(_translate("AmortsWindow", "Максимальная температура (℃)"))
        self.lbl_txt5.setText(_translate("AmortsWindow", "Минимальное усилие сжатия (кгс)"))
        self.lbl_recoil_min.setText(_translate("AmortsWindow", "0"))
        self.lbl_txt3.setText(_translate("AmortsWindow", "ПАРАМЕТРЫ"))
        self.lbl_length_min.setText(_translate("AmortsWindow", "0"))
        self.lbl_temper.setText(_translate("AmortsWindow", "0"))
        self.lbl_length_max.setText(_translate("AmortsWindow", "0"))
        self.lbl_txt4.setText(_translate("AmortsWindow", "Длина в сжатом состоянии (мм)"))
        self.lbl_txt6.setText(_translate("AmortsWindow", "Минимальное усилие отбоя (кгс)"))
        self.lbl_comp_min.setText(_translate("AmortsWindow", "0"))
        self.lbl_recoil_max.setText(_translate("AmortsWindow", "0"))
        self.lbl_txt4_2.setText(_translate("AmortsWindow", "Длина в растянутом состоянии (мм)"))
        self.lbl_txt5_2.setText(_translate("AmortsWindow", "Максимальное усилие сжатия (кгс)"))
        self.lbl_txt6_2.setText(_translate("AmortsWindow", "Максимальная усилие отбоя (кгс)"))
        self.lbl_txt4_3.setText(_translate("AmortsWindow", "Ход (мм)"))
        self.lbl_hod.setText(_translate("AmortsWindow", "0"))
        self.lbl_txt4_4.setText(_translate("AmortsWindow", "Скорость испытания (м/с)"))
        self.lbl_speed_1.setText(_translate("AmortsWindow", "0"))
        self.lbl_txt4_6.setText(_translate("AmortsWindow", "Адаптер (№)"))
        self.lbl_adapter.setText(_translate("AmortsWindow", "0"))
        self.lbl_speed_2.setText(_translate("AmortsWindow", "0"))
        self.lbl_comp_min_2.setText(_translate("AmortsWindow", "0"))
        self.lbl_comp_max_2.setText(_translate("AmortsWindow", "0"))
        self.lbl_recoil_min_2.setText(_translate("AmortsWindow", "0"))
        self.lbl_recoil_max_2.setText(_translate("AmortsWindow", "0"))
        self.btn_add.setText(_translate("AmortsWindow", "Добавить"))
        self.btn_change.setText(_translate("AmortsWindow", "Изменить"))
        self.btn_del.setText(_translate("AmortsWindow", "Удалить"))
        self.btn_exit.setText(_translate("AmortsWindow", "Выход"))
        self.txt_quest.setMarkdown(_translate("AmortsWindow", "**ИНФОРМАЦИЯ**\n"
"\n"
""))
        self.txt_quest.setHtml(_translate("AmortsWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:20pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:13px; margin-bottom:13px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ИНФОРМАЦИЯ</p></body></html>"))
        self.btn_ok_quest.setText(_translate("AmortsWindow", "Ok"))
        self.btn_cancel_quest.setText(_translate("AmortsWindow", "Отмена"))
        self.txt_warning.setMarkdown(_translate("AmortsWindow", "**ПРЕДУПРЕЖДЕНИЕ**\n"
"\n"
""))
        self.txt_warning.setHtml(_translate("AmortsWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:20pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:13px; margin-bottom:13px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ПРЕДУПРЕЖДЕНИЕ</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:13px; margin-bottom:13px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_ok_warning.setText(_translate("AmortsWindow", "Ok"))
