# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from modified_ui_obj.click_lineedit import MyLineEdit


class UiSettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(610, 725)
        SettingsWindow.setMinimumSize(QtCore.QSize(610, 725))
        SettingsWindow.setMaximumSize(QtCore.QSize(610, 725))
        SettingsWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(SettingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.clear_force_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.clear_force_lcd.setGeometry(QtCore.QRect(160, 54, 101, 43))
        self.clear_force_lcd.setStyleSheet("color: rgb(0, 0, 0);")
        self.clear_force_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.clear_force_lcd.setProperty("value", -100.0)
        self.clear_force_lcd.setProperty("intValue", -100)
        self.clear_force_lcd.setObjectName("clear_force_lcd")
        self._lbl_txt2 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt2.setGeometry(QtCore.QRect(10, 58, 141, 32))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt2.setFont(font)
        self._lbl_txt2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._lbl_txt2.setObjectName("_lbl_txt2")
        self._lbl_txt1 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt1.setGeometry(QtCore.QRect(38, 16, 113, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt1.setFont(font)
        self._lbl_txt1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._lbl_txt1.setObjectName("_lbl_txt1")
        self.lcdTime = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdTime.setGeometry(QtCore.QRect(160, 8, 101, 43))
        self.lcdTime.setStyleSheet("color: rgb(0, 0, 0);")
        self.lcdTime.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdTime.setProperty("value", 0.0)
        self.lcdTime.setProperty("intValue", 0)
        self.lcdTime.setObjectName("lcdTime")
        self.fram_cycle_F = QtWidgets.QLabel(self.centralwidget)
        self.fram_cycle_F.setGeometry(QtCore.QRect(320, 12, 25, 25))
        self.fram_cycle_F.setMinimumSize(QtCore.QSize(20, 20))
        self.fram_cycle_F.setMaximumSize(QtCore.QSize(25, 25))
        self.fram_cycle_F.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.fram_cycle_F.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fram_cycle_F.setText("")
        self.fram_cycle_F.setObjectName("fram_cycle_F")
        self.btn_cycle_F = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cycle_F.setGeometry(QtCore.QRect(280, 10, 30, 30))
        self.btn_cycle_F.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_cycle_F.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_cycle_F.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    background-color: rgb(0, 255, 0)\n"
"    \n"
"}")
        self.btn_cycle_F.setText("")
        self.btn_cycle_F.setCheckable(False)
        self.btn_cycle_F.setChecked(False)
        self.btn_cycle_F.setObjectName("btn_cycle_F")
        self._lbl_txt3 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt3.setGeometry(QtCore.QRect(350, 12, 243, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt3.setFont(font)
        self._lbl_txt3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._lbl_txt3.setObjectName("_lbl_txt3")
        self._lbl_txt5 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt5.setGeometry(QtCore.QRect(350, 47, 243, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt5.setFont(font)
        self._lbl_txt5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._lbl_txt5.setObjectName("_lbl_txt5")
        self.fram_no_control = QtWidgets.QLabel(self.centralwidget)
        self.fram_no_control.setGeometry(QtCore.QRect(320, 47, 25, 25))
        self.fram_no_control.setMinimumSize(QtCore.QSize(20, 20))
        self.fram_no_control.setMaximumSize(QtCore.QSize(25, 25))
        self.fram_no_control.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.fram_no_control.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fram_no_control.setText("")
        self.fram_no_control.setObjectName("fram_no_control")
        self.btn_no_control = QtWidgets.QPushButton(self.centralwidget)
        self.btn_no_control.setGeometry(QtCore.QRect(280, 45, 30, 30))
        self.btn_no_control.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_no_control.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_no_control.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    background-color: rgb(0, 255, 0)\n"
"    \n"
"}")
        self.btn_no_control.setText("")
        self.btn_no_control.setCheckable(False)
        self.btn_no_control.setChecked(False)
        self.btn_no_control.setObjectName("btn_no_control")
        self.btn_max_F = QtWidgets.QPushButton(self.centralwidget)
        self.btn_max_F.setGeometry(QtCore.QRect(280, 80, 30, 30))
        self.btn_max_F.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_max_F.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_max_F.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    background-color: rgb(0, 255, 0)\n"
"    \n"
"}")
        self.btn_max_F.setText("")
        self.btn_max_F.setCheckable(False)
        self.btn_max_F.setChecked(False)
        self.btn_max_F.setObjectName("btn_max_F")
        self.fram_max_F = QtWidgets.QLabel(self.centralwidget)
        self.fram_max_F.setGeometry(QtCore.QRect(320, 82, 25, 25))
        self.fram_max_F.setMinimumSize(QtCore.QSize(20, 20))
        self.fram_max_F.setMaximumSize(QtCore.QSize(25, 25))
        self.fram_max_F.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.fram_max_F.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fram_max_F.setText("")
        self.fram_max_F.setObjectName("fram_max_F")
        self._lbl_txt6 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt6.setGeometry(QtCore.QRect(350, 82, 243, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt6.setFont(font)
        self._lbl_txt6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._lbl_txt6.setObjectName("_lbl_txt6")
        self._lbl_txt8 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt8.setGeometry(QtCore.QRect(350, 367, 243, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt8.setFont(font)
        self._lbl_txt8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._lbl_txt8.setObjectName("_lbl_txt8")
        self.fram_down_point = QtWidgets.QLabel(self.centralwidget)
        self.fram_down_point.setGeometry(QtCore.QRect(320, 367, 25, 25))
        self.fram_down_point.setMinimumSize(QtCore.QSize(20, 20))
        self.fram_down_point.setMaximumSize(QtCore.QSize(25, 25))
        self.fram_down_point.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.fram_down_point.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fram_down_point.setText("")
        self.fram_down_point.setObjectName("fram_down_point")
        self.fram_up_point = QtWidgets.QLabel(self.centralwidget)
        self.fram_up_point.setGeometry(QtCore.QRect(320, 402, 25, 25))
        self.fram_up_point.setMinimumSize(QtCore.QSize(20, 20))
        self.fram_up_point.setMaximumSize(QtCore.QSize(25, 25))
        self.fram_up_point.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.fram_up_point.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fram_up_point.setText("")
        self.fram_up_point.setObjectName("fram_up_point")
        self._lbl_txt9 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt9.setGeometry(QtCore.QRect(350, 402, 243, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt9.setFont(font)
        self._lbl_txt9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._lbl_txt9.setObjectName("_lbl_txt9")
        self._lbl_txt10 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt10.setGeometry(QtCore.QRect(350, 262, 243, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt10.setFont(font)
        self._lbl_txt10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._lbl_txt10.setObjectName("_lbl_txt10")
        self.fram_safety_fence = QtWidgets.QLabel(self.centralwidget)
        self.fram_safety_fence.setGeometry(QtCore.QRect(320, 262, 25, 25))
        self.fram_safety_fence.setMinimumSize(QtCore.QSize(20, 20))
        self.fram_safety_fence.setMaximumSize(QtCore.QSize(25, 25))
        self.fram_safety_fence.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.fram_safety_fence.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fram_safety_fence.setText("")
        self.fram_safety_fence.setObjectName("fram_safety_fence")
        self.fram_condition_FC = QtWidgets.QLabel(self.centralwidget)
        self.fram_condition_FC.setGeometry(QtCore.QRect(320, 297, 25, 25))
        self.fram_condition_FC.setMinimumSize(QtCore.QSize(20, 20))
        self.fram_condition_FC.setMaximumSize(QtCore.QSize(25, 25))
        self.fram_condition_FC.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.fram_condition_FC.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fram_condition_FC.setText("")
        self.fram_condition_FC.setObjectName("fram_condition_FC")
        self._lbl_txt11 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt11.setGeometry(QtCore.QRect(350, 297, 243, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt11.setFont(font)
        self._lbl_txt11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._lbl_txt11.setObjectName("_lbl_txt11")
        self._lbl_txt12 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt12.setGeometry(QtCore.QRect(350, 332, 243, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt12.setFont(font)
        self._lbl_txt12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._lbl_txt12.setObjectName("_lbl_txt12")
        self.fram_sensor_F = QtWidgets.QLabel(self.centralwidget)
        self.fram_sensor_F.setGeometry(QtCore.QRect(320, 332, 25, 25))
        self.fram_sensor_F.setMinimumSize(QtCore.QSize(20, 20))
        self.fram_sensor_F.setMaximumSize(QtCore.QSize(25, 25))
        self.fram_sensor_F.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.fram_sensor_F.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fram_sensor_F.setText("")
        self.fram_sensor_F.setObjectName("fram_sensor_F")
        self._lbl_txt15 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt15.setGeometry(QtCore.QRect(10, 192, 143, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt15.setFont(font)
        self._lbl_txt15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._lbl_txt15.setObjectName("_lbl_txt15")
        self.lcdH = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdH.setGeometry(QtCore.QRect(160, 192, 101, 43))
        self.lcdH.setStyleSheet("color: rgb(0, 0, 0);")
        self.lcdH.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdH.setProperty("value", 0.0)
        self.lcdH.setProperty("intValue", 0)
        self.lcdH.setObjectName("lcdH")
        self._lbl_txt15_2 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt15_2.setGeometry(QtCore.QRect(10, 285, 143, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self._lbl_txt15_2.setFont(font)
        self._lbl_txt15_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt15_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._lbl_txt15_2.setObjectName("_lbl_txt15_2")
        self.lcdTemp_1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdTemp_1.setGeometry(QtCore.QRect(160, 284, 101, 43))
        self.lcdTemp_1.setStyleSheet("color: rgb(0, 0, 0);")
        self.lcdTemp_1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdTemp_1.setProperty("value", 0.0)
        self.lcdTemp_1.setProperty("intValue", 0)
        self.lcdTemp_1.setObjectName("lcdTemp_1")
        self.fram_block_traverse_1 = QtWidgets.QLabel(self.centralwidget)
        self.fram_block_traverse_1.setGeometry(QtCore.QRect(320, 437, 25, 25))
        self.fram_block_traverse_1.setMinimumSize(QtCore.QSize(20, 20))
        self.fram_block_traverse_1.setMaximumSize(QtCore.QSize(25, 25))
        self.fram_block_traverse_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.fram_block_traverse_1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fram_block_traverse_1.setText("")
        self.fram_block_traverse_1.setObjectName("fram_block_traverse_1")
        self._lbl_txt8_2 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt8_2.setGeometry(QtCore.QRect(350, 437, 243, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt8_2.setFont(font)
        self._lbl_txt8_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt8_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._lbl_txt8_2.setObjectName("_lbl_txt8_2")
        self.fram_block_traverse_2 = QtWidgets.QLabel(self.centralwidget)
        self.fram_block_traverse_2.setGeometry(QtCore.QRect(320, 472, 25, 25))
        self.fram_block_traverse_2.setMinimumSize(QtCore.QSize(20, 20))
        self.fram_block_traverse_2.setMaximumSize(QtCore.QSize(25, 25))
        self.fram_block_traverse_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.fram_block_traverse_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fram_block_traverse_2.setText("")
        self.fram_block_traverse_2.setObjectName("fram_block_traverse_2")
        self._lbl_txt9_2 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt9_2.setGeometry(QtCore.QRect(350, 472, 243, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt9_2.setFont(font)
        self._lbl_txt9_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt9_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._lbl_txt9_2.setObjectName("_lbl_txt9_2")
        self.fram_down__alarm_point = QtWidgets.QLabel(self.centralwidget)
        self.fram_down__alarm_point.setGeometry(QtCore.QRect(320, 507, 25, 25))
        self.fram_down__alarm_point.setMinimumSize(QtCore.QSize(20, 20))
        self.fram_down__alarm_point.setMaximumSize(QtCore.QSize(25, 25))
        self.fram_down__alarm_point.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.fram_down__alarm_point.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fram_down__alarm_point.setText("")
        self.fram_down__alarm_point.setObjectName("fram_down__alarm_point")
        self._lbl_txt8_3 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt8_3.setGeometry(QtCore.QRect(350, 503, 243, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt8_3.setFont(font)
        self._lbl_txt8_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt8_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._lbl_txt8_3.setObjectName("_lbl_txt8_3")
        self.fram_up_alarm_point = QtWidgets.QLabel(self.centralwidget)
        self.fram_up_alarm_point.setGeometry(QtCore.QRect(320, 542, 25, 25))
        self.fram_up_alarm_point.setMinimumSize(QtCore.QSize(20, 20))
        self.fram_up_alarm_point.setMaximumSize(QtCore.QSize(25, 25))
        self.fram_up_alarm_point.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.fram_up_alarm_point.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fram_up_alarm_point.setText("")
        self.fram_up_alarm_point.setObjectName("fram_up_alarm_point")
        self._lbl_txt9_3 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt9_3.setGeometry(QtCore.QRect(350, 540, 243, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt9_3.setFont(font)
        self._lbl_txt9_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt9_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._lbl_txt9_3.setObjectName("_lbl_txt9_3")
        self.lcdH_T = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdH_T.setGeometry(QtCore.QRect(160, 238, 101, 43))
        self.lcdH_T.setStyleSheet("color: rgb(0, 0, 0);")
        self.lcdH_T.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdH_T.setProperty("value", 0.0)
        self.lcdH_T.setProperty("intValue", 0)
        self.lcdH_T.setObjectName("lcdH_T")
        self._lbl_txt15_3 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt15_3.setGeometry(QtCore.QRect(10, 238, 143, 35))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self._lbl_txt15_3.setFont(font)
        self._lbl_txt15_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt15_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._lbl_txt15_3.setObjectName("_lbl_txt15_3")
        self._lbl_txt5_2 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt5_2.setGeometry(QtCore.QRect(350, 222, 243, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt5_2.setFont(font)
        self._lbl_txt5_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt5_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._lbl_txt5_2.setObjectName("_lbl_txt5_2")
        self.fram_green_light = QtWidgets.QLabel(self.centralwidget)
        self.fram_green_light.setGeometry(QtCore.QRect(320, 222, 25, 25))
        self.fram_green_light.setMinimumSize(QtCore.QSize(20, 20))
        self.fram_green_light.setMaximumSize(QtCore.QSize(25, 25))
        self.fram_green_light.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.fram_green_light.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fram_green_light.setText("")
        self.fram_green_light.setObjectName("fram_green_light")
        self._lbl_txt6_2 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt6_2.setGeometry(QtCore.QRect(350, 185, 243, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt6_2.setFont(font)
        self._lbl_txt6_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt6_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._lbl_txt6_2.setObjectName("_lbl_txt6_2")
        self.fram_red_light = QtWidgets.QLabel(self.centralwidget)
        self.fram_red_light.setGeometry(QtCore.QRect(320, 187, 25, 25))
        self.fram_red_light.setMinimumSize(QtCore.QSize(20, 20))
        self.fram_red_light.setMaximumSize(QtCore.QSize(25, 25))
        self.fram_red_light.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.fram_red_light.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fram_red_light.setText("")
        self.fram_red_light.setObjectName("fram_red_light")
        self.btn_green_light = QtWidgets.QPushButton(self.centralwidget)
        self.btn_green_light.setGeometry(QtCore.QRect(280, 220, 30, 30))
        self.btn_green_light.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_green_light.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_green_light.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    background-color: rgb(0, 255, 0)\n"
"    \n"
"}")
        self.btn_green_light.setText("")
        self.btn_green_light.setCheckable(False)
        self.btn_green_light.setChecked(False)
        self.btn_green_light.setObjectName("btn_green_light")
        self.btn_red_light = QtWidgets.QPushButton(self.centralwidget)
        self.btn_red_light.setGeometry(QtCore.QRect(280, 185, 30, 30))
        self.btn_red_light.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_red_light.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_red_light.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    background-color: rgb(0, 255, 0)\n"
"    \n"
"}")
        self.btn_red_light.setText("")
        self.btn_red_light.setCheckable(False)
        self.btn_red_light.setChecked(False)
        self.btn_red_light.setObjectName("btn_red_light")
        self._lbl_txt15_4 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt15_4.setGeometry(QtCore.QRect(10, 380, 143, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self._lbl_txt15_4.setFont(font)
        self._lbl_txt15_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt15_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._lbl_txt15_4.setObjectName("_lbl_txt15_4")
        self.lineEdit_F_alarm = MyLineEdit(self.centralwidget)
        self.lineEdit_F_alarm.setGeometry(QtCore.QRect(160, 378, 101, 43))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_F_alarm.setFont(font)
        self.lineEdit_F_alarm.setText("")
        self.lineEdit_F_alarm.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_F_alarm.setObjectName("lineEdit_F_alarm")
        self.fram_yellow_btn = QtWidgets.QLabel(self.centralwidget)
        self.fram_yellow_btn.setGeometry(QtCore.QRect(320, 580, 25, 25))
        self.fram_yellow_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.fram_yellow_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.fram_yellow_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.fram_yellow_btn.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fram_yellow_btn.setText("")
        self.fram_yellow_btn.setObjectName("fram_yellow_btn")
        self._lbl_txt6_3 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt6_3.setGeometry(QtCore.QRect(350, 580, 243, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt6_3.setFont(font)
        self._lbl_txt6_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt6_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._lbl_txt6_3.setObjectName("_lbl_txt6_3")
        self.btn_temper_channel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_temper_channel.setGeometry(QtCore.QRect(280, 115, 30, 30))
        self.btn_temper_channel.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_temper_channel.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_temper_channel.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    background-color: rgb(0, 255, 0)\n"
"    \n"
"}")
        self.btn_temper_channel.setText("")
        self.btn_temper_channel.setCheckable(False)
        self.btn_temper_channel.setChecked(False)
        self.btn_temper_channel.setObjectName("btn_temper_channel")
        self.lbl_temp_sens = QtWidgets.QLabel(self.centralwidget)
        self.lbl_temp_sens.setGeometry(QtCore.QRect(320, 117, 281, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lbl_temp_sens.setFont(font)
        self.lbl_temp_sens.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_temp_sens.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_temp_sens.setObjectName("lbl_temp_sens")
        self.freq_frame = QtWidgets.QFrame(self.centralwidget)
        self.freq_frame.setGeometry(QtCore.QRect(10, 430, 301, 271))
        self.freq_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.freq_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.freq_frame.setObjectName("freq_frame")
        self._lbl_txt1_3 = QtWidgets.QLabel(self.freq_frame)
        self._lbl_txt1_3.setGeometry(QtCore.QRect(210, 0, 70, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt1_3.setFont(font)
        self._lbl_txt1_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt1_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._lbl_txt1_3.setObjectName("_lbl_txt1_3")
        self._lbl_txt1_2 = QtWidgets.QLabel(self.freq_frame)
        self._lbl_txt1_2.setGeometry(QtCore.QRect(107, 0, 50, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt1_2.setFont(font)
        self._lbl_txt1_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._lbl_txt1_2.setObjectName("_lbl_txt1_2")
        self._lbl_txt19_2 = QtWidgets.QLabel(self.freq_frame)
        self._lbl_txt19_2.setGeometry(QtCore.QRect(13, 60, 90, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self._lbl_txt19_2.setFont(font)
        self._lbl_txt19_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt19_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._lbl_txt19_2.setObjectName("_lbl_txt19_2")
        self._lbl_txt19 = QtWidgets.QLabel(self.freq_frame)
        self._lbl_txt19.setGeometry(QtCore.QRect(13, 25, 90, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt19.setFont(font)
        self._lbl_txt19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._lbl_txt19.setObjectName("_lbl_txt19")
        self.btn_hod = QtWidgets.QPushButton(self.freq_frame)
        self.btn_hod.setGeometry(QtCore.QRect(165, 25, 30, 30))
        self.btn_hod.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_hod.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_hod.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    background-color: rgb(0, 255, 0)\n"
"    \n"
"}")
        self.btn_hod.setText("")
        self.btn_hod.setCheckable(False)
        self.btn_hod.setChecked(False)
        self.btn_hod.setObjectName("btn_hod")
        self.lineEdit_hod = QtWidgets.QLineEdit(self.freq_frame)
        self.lineEdit_hod.setGeometry(QtCore.QRect(110, 25, 50, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_hod.setFont(font)
        self.lineEdit_hod.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_hod.setObjectName("lineEdit_hod")
        self.btn_freq_trverse = QtWidgets.QPushButton(self.freq_frame)
        self.btn_freq_trverse.setGeometry(QtCore.QRect(265, 50, 30, 30))
        self.btn_freq_trverse.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_freq_trverse.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_freq_trverse.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    background-color: rgb(0, 255, 0)\n"
"    \n"
"}")
        self.btn_freq_trverse.setText("")
        self.btn_freq_trverse.setCheckable(False)
        self.btn_freq_trverse.setChecked(False)
        self.btn_freq_trverse.setObjectName("btn_freq_trverse")
        self.btn_speed_main = QtWidgets.QPushButton(self.freq_frame)
        self.btn_speed_main.setGeometry(QtCore.QRect(165, 60, 30, 30))
        self.btn_speed_main.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_speed_main.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_speed_main.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    background-color: rgb(0, 255, 0)\n"
"    \n"
"}")
        self.btn_speed_main.setText("")
        self.btn_speed_main.setCheckable(False)
        self.btn_speed_main.setChecked(False)
        self.btn_speed_main.setObjectName("btn_speed_main")
        self.lineEdit_freq_traverse = QtWidgets.QLineEdit(self.freq_frame)
        self.lineEdit_freq_traverse.setGeometry(QtCore.QRect(210, 50, 50, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_freq_traverse.setFont(font)
        self.lineEdit_freq_traverse.setText("")
        self.lineEdit_freq_traverse.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_freq_traverse.setObjectName("lineEdit_freq_traverse")
        self.lineEdit_speed_main = QtWidgets.QLineEdit(self.freq_frame)
        self.lineEdit_speed_main.setGeometry(QtCore.QRect(110, 60, 50, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_speed_main.setFont(font)
        self.lineEdit_speed_main.setText("")
        self.lineEdit_speed_main.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_speed_main.setObjectName("lineEdit_speed_main")
        self._lbl_txt1_4 = QtWidgets.QLabel(self.freq_frame)
        self._lbl_txt1_4.setGeometry(QtCore.QRect(205, 25, 90, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt1_4.setFont(font)
        self._lbl_txt1_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt1_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._lbl_txt1_4.setObjectName("_lbl_txt1_4")
        self.btn_motor_up = QtWidgets.QPushButton(self.freq_frame)
        self.btn_motor_up.setGeometry(QtCore.QRect(220, 90, 60, 30))
        self.btn_motor_up.setMinimumSize(QtCore.QSize(60, 30))
        self.btn_motor_up.setMaximumSize(QtCore.QSize(60, 50))
        self.btn_motor_up.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"")
        self.btn_motor_up.setCheckable(False)
        self.btn_motor_up.setChecked(False)
        self.btn_motor_up.setObjectName("btn_motor_up")
        self.btn_motor_down = QtWidgets.QPushButton(self.freq_frame)
        self.btn_motor_down.setGeometry(QtCore.QRect(220, 130, 60, 30))
        self.btn_motor_down.setMinimumSize(QtCore.QSize(60, 30))
        self.btn_motor_down.setMaximumSize(QtCore.QSize(60, 50))
        self.btn_motor_down.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"")
        self.btn_motor_down.setCheckable(False)
        self.btn_motor_down.setChecked(False)
        self.btn_motor_down.setObjectName("btn_motor_down")
        self.btn_motor_traverse_stop = QtWidgets.QPushButton(self.freq_frame)
        self.btn_motor_traverse_stop.setGeometry(QtCore.QRect(220, 170, 60, 60))
        self.btn_motor_traverse_stop.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_motor_traverse_stop.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_motor_traverse_stop.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"")
        self.btn_motor_traverse_stop.setCheckable(False)
        self.btn_motor_traverse_stop.setChecked(False)
        self.btn_motor_traverse_stop.setObjectName("btn_motor_traverse_stop")
        self.btn_motor_main_start = QtWidgets.QPushButton(self.freq_frame)
        self.btn_motor_main_start.setGeometry(QtCore.QRect(80, 100, 80, 50))
        self.btn_motor_main_start.setMinimumSize(QtCore.QSize(80, 50))
        self.btn_motor_main_start.setMaximumSize(QtCore.QSize(80, 50))
        self.btn_motor_main_start.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"")
        self.btn_motor_main_start.setCheckable(False)
        self.btn_motor_main_start.setChecked(False)
        self.btn_motor_main_start.setObjectName("btn_motor_main_start")
        self.btn_motor_main_stop = QtWidgets.QPushButton(self.freq_frame)
        self.btn_motor_main_stop.setGeometry(QtCore.QRect(80, 160, 80, 50))
        self.btn_motor_main_stop.setMinimumSize(QtCore.QSize(80, 50))
        self.btn_motor_main_stop.setMaximumSize(QtCore.QSize(80, 50))
        self.btn_motor_main_stop.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"")
        self.btn_motor_main_stop.setCheckable(False)
        self.btn_motor_main_stop.setChecked(False)
        self.btn_motor_main_stop.setObjectName("btn_motor_main_stop")
        self.btn_test = QtWidgets.QPushButton(self.freq_frame)
        self.btn_test.setGeometry(QtCore.QRect(20, 228, 30, 30))
        self.btn_test.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_test.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_test.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    background-color: rgb(0, 255, 0)\n"
"    \n"
"}")
        self.btn_test.setText("")
        self.btn_test.setCheckable(True)
        self.btn_test.setChecked(False)
        self.btn_test.setObjectName("btn_test")
        self._lbl_txt10_3 = QtWidgets.QLabel(self.freq_frame)
        self._lbl_txt10_3.setGeometry(QtCore.QRect(60, 230, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt10_3.setFont(font)
        self._lbl_txt10_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt10_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._lbl_txt10_3.setObjectName("_lbl_txt10_3")
        self.lcdTemp_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdTemp_2.setGeometry(QtCore.QRect(160, 330, 101, 43))
        self.lcdTemp_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.lcdTemp_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdTemp_2.setProperty("value", 0.0)
        self.lcdTemp_2.setProperty("intValue", 0)
        self.lcdTemp_2.setObjectName("lcdTemp_2")
        self._lbl_txt15_5 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt15_5.setGeometry(QtCore.QRect(10, 332, 143, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self._lbl_txt15_5.setFont(font)
        self._lbl_txt15_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt15_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._lbl_txt15_5.setObjectName("_lbl_txt15_5")
        self.koef_force_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.koef_force_lcd.setGeometry(QtCore.QRect(160, 100, 101, 43))
        self.koef_force_lcd.setStyleSheet("color: rgb(0, 0, 0);")
        self.koef_force_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.koef_force_lcd.setProperty("value", -100.0)
        self.koef_force_lcd.setProperty("intValue", -100)
        self.koef_force_lcd.setObjectName("koef_force_lcd")
        self._lbl_txt2_2 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt2_2.setGeometry(QtCore.QRect(10, 104, 141, 32))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt2_2.setFont(font)
        self._lbl_txt2_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt2_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._lbl_txt2_2.setObjectName("_lbl_txt2_2")
        self.correct_force_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.correct_force_lcd.setGeometry(QtCore.QRect(160, 146, 101, 43))
        self.correct_force_lcd.setStyleSheet("color: rgb(0, 0, 0);")
        self.correct_force_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.correct_force_lcd.setProperty("value", -100.0)
        self.correct_force_lcd.setProperty("intValue", -100)
        self.correct_force_lcd.setObjectName("correct_force_lcd")
        self._lbl_txt2_3 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt2_3.setGeometry(QtCore.QRect(10, 150, 141, 32))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt2_3.setFont(font)
        self._lbl_txt2_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt2_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._lbl_txt2_3.setObjectName("_lbl_txt2_3")
        self.btn_correct_force = QtWidgets.QPushButton(self.centralwidget)
        self.btn_correct_force.setGeometry(QtCore.QRect(280, 150, 30, 30))
        self.btn_correct_force.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_correct_force.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_correct_force.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(207, 207, 207, 255));\n"
"\n"
"    border: 1px rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"    border-style: outset;\n"
"\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0227273, x2:0.489, y2:1, stop:0 rgba(234, 246, 253, 255), stop:1 rgba(169, 219, 246, 255));\n"
"    \n"
"}\n"
"    \n"
"\n"
"QPushButton:checked\n"
"{\n"
"    background-color: rgb(0, 255, 0)\n"
"    \n"
"}")
        self.btn_correct_force.setText("")
        self.btn_correct_force.setCheckable(False)
        self.btn_correct_force.setChecked(False)
        self.btn_correct_force.setObjectName("btn_correct_force")
        self._lbl_txt3_2 = QtWidgets.QLabel(self.centralwidget)
        self._lbl_txt3_2.setGeometry(QtCore.QRect(320, 152, 243, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self._lbl_txt3_2.setFont(font)
        self._lbl_txt3_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._lbl_txt3_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self._lbl_txt3_2.setObjectName("_lbl_txt3_2")
        SettingsWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SettingsWindow)
        self.statusbar.setObjectName("statusbar")
        SettingsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "HandDebug"))
        self._lbl_txt2.setText(_translate("SettingsWindow", "Чистое усилие (кгс):"))
        self._lbl_txt1.setText(_translate("SettingsWindow", "Время (мс):"))
        self._lbl_txt3.setText(_translate("SettingsWindow", "Циклический опрос датчика силы"))
        self._lbl_txt5.setText(_translate("SettingsWindow", "Потеря управления"))
        self._lbl_txt6.setText(_translate("SettingsWindow", "Превышение усилия"))
        self._lbl_txt8.setText(_translate("SettingsWindow", "Нижнее положение траверсы"))
        self._lbl_txt9.setText(_translate("SettingsWindow", "Верхнее положение траверсы"))
        self._lbl_txt10.setText(_translate("SettingsWindow", "Защитное ограждение открыто"))
        self._lbl_txt11.setText(_translate("SettingsWindow", "ПЧ занят для приема команд"))
        self._lbl_txt12.setText(_translate("SettingsWindow", "Датчик усилия занят"))
        self._lbl_txt15.setText(_translate("SettingsWindow", "Перемещение\n"
"шатуна (мм):"))
        self._lbl_txt15_2.setText(_translate("SettingsWindow", "Бесконтактный\n"
"датчик (°С):"))
        self._lbl_txt8_2.setText(_translate("SettingsWindow", "Блокировка траверсы 1"))
        self._lbl_txt9_2.setText(_translate("SettingsWindow", "Блокировка траверсы 2"))
        self._lbl_txt8_3.setText(_translate("SettingsWindow", "Нижнее аварийное\n"
"положение траверсы"))
        self._lbl_txt9_3.setText(_translate("SettingsWindow", "Верхнее аварийное\n"
"положение траверсы"))
        self._lbl_txt15_3.setText(_translate("SettingsWindow", "Перемещение\n"
"траверсы (мм):"))
        self._lbl_txt5_2.setText(_translate("SettingsWindow", "Зелёный индикатор"))
        self._lbl_txt6_2.setText(_translate("SettingsWindow", "Красный индикатор"))
        self._lbl_txt15_4.setText(_translate("SettingsWindow", "Аварийное\n"
"усилие (кгс):"))
        self._lbl_txt6_3.setText(_translate("SettingsWindow", "Кнопка ПУСК/ОСТАНОВ"))
        self.lbl_temp_sens.setText(_translate("SettingsWindow", "Бесконтактный температурный датчик"))
        self._lbl_txt1_3.setText(_translate("SettingsWindow", "Траверса"))
        self._lbl_txt1_2.setText(_translate("SettingsWindow", "Шатун"))
        self._lbl_txt19_2.setText(_translate("SettingsWindow", "Скорость, (м/с)"))
        self._lbl_txt19.setText(_translate("SettingsWindow", "Ход, (мм)"))
        self.lineEdit_hod.setText(_translate("SettingsWindow", "50"))
        self._lbl_txt1_4.setText(_translate("SettingsWindow", "Частота, (Гц)"))
        self.btn_motor_up.setText(_translate("SettingsWindow", "ВВЕРХ"))
        self.btn_motor_down.setText(_translate("SettingsWindow", "ВНИЗ"))
        self.btn_motor_traverse_stop.setText(_translate("SettingsWindow", "СТОП"))
        self.btn_motor_main_start.setText(_translate("SettingsWindow", "СТАРТ\n"
"ПРИВОД"))
        self.btn_motor_main_stop.setText(_translate("SettingsWindow", "СТОП\n"
"ПРИВОД"))
        self._lbl_txt10_3.setText(_translate("SettingsWindow", "Чтение буфера"))
        self._lbl_txt15_5.setText(_translate("SettingsWindow", "Контактный\n"
"датчик (°С):"))
        self._lbl_txt2_2.setText(_translate("SettingsWindow", "Скорректированное\n"
"усилие (кгс):"))
        self._lbl_txt2_3.setText(_translate("SettingsWindow", "Обнулённое\n"
"усилие (кгс):"))
        self._lbl_txt3_2.setText(_translate("SettingsWindow", "Обнулить датчик силы"))
